// <auto-generated />
namespace AuctionPlanet.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SeparatedImagesFromLots : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeparatedImagesFromLots));
        
        string IMigrationMetadata.Id
        {
            get { return "201510101839419_SeparatedImagesFromLots"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
